slack_channel_id: C080138T9S6
service_account_key_raw: service_account_key_raw.json
service_account_key_analytics: service_account_key_analytics.json
turn_headers: turn_auth.json
project_raw: noorahealth-raw
project_analytics: noorahealth-analytics
bucket_name: noora_test_bucket