name: Sync Whatsapp Attachments

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_PARAMS: ${{ secrets.TURN_ATTACHMENTS }}
      SERVICE_ACCOUNT_KEY_RAW: ${{ secrets.SERVICE_ACCOUNT_KEY_RAW }}
      SERVICE_ACCOUNT_KEY_ANALYTICS: ${{ secrets.SERVICE_ACCOUNT_KEY_ANALYTICS }}
      TURN_AUTH: ${{ secrets.TURN_AUTH }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run script
        run: uv run -m src.turn_attachments
