name: Sync Whatsapp Attachments

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      past_hours:
        required: false
        type: choice
        options:
          - 25
          - 75
          - 170
          
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_PARAMS: ${{ secrets.TURN_ATTACHMENTS }}
      SERVICE_ACCOUNT_KEY_RAW: ${{ secrets.SERVICE_ACCOUNT_KEY_RAW }}
      SERVICE_ACCOUNT_KEY_ANALYTICS: ${{ secrets.SERVICE_ACCOUNT_KEY_ANALYTICS }}
      TURN_HEADERS: ${{ secrets.TURN_HEADERS }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      PAST_HOURS: ${{ inputs.past_hours || '25' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install the Project
        run: uv sync --locked

      - name: Run script
        run: uv run -m src.turn_attachments --past-hours $PAST_HOURS
        #run: uv run python src/turn_attachments.py
